name: fam_intento1
description: "Proyecto fam_intento1."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:                      # 👈 configuración del ícono
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # ruta de tu ícono personalizado
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/miembros/amdes/
    - assets/images/miembros/acobol/
    - assets/images/miembros/amb/
    - assets/ministros.json
    - assets/images/departamentos/
    - assets/images/miembros/amdes/lapaz/
    - assets/images/miembros/amdes/santacruz/
    - assets/images/miembros/amdes/cochabamba/
    - assets/images/miembros/amdes/oruro/
    - assets/images/miembros/amdes/potosi/
    - assets/images/miembros/amdes/pando/
    - assets/images/miembros/amdes/beni/
    - assets/images/miembros/amdes/chuquisaca/
    - assets/images/miembros/amdes/tarija/



