// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASfcDcr76cW8AFIArvZ4QAS89RGOnmNLM',
    appId: '1:624760631876:web:a3c47fc955420850068211',
    messagingSenderId: '624760631876',
    projectId: 'app-fam-7d4f6',
    authDomain: 'app-fam-7d4f6.firebaseapp.com',
    storageBucket: 'app-fam-7d4f6.firebasestorage.app',
    measurementId: 'G-1DNCS0PRJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnj1nmeChDvJull99NbZ4HALAWmvFG53c',
    appId: '1:624760631876:android:0920b8f1313bac19068211',
    messagingSenderId: '624760631876',
    projectId: 'app-fam-7d4f6',
    storageBucket: 'app-fam-7d4f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLzFbvBMh2z8ePCO1hJQrw-LNuml5Zuk',
    appId: '1:624760631876:ios:eaea7f3ae2095547068211',
    messagingSenderId: '624760631876',
    projectId: 'app-fam-7d4f6',
    storageBucket: 'app-fam-7d4f6.firebasestorage.app',
    iosClientId: '624760631876-2hi7bn5niibj3gl9f6g69o73l239dnnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.famIntento1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLzFbvBMh2z8ePCO1hJQrw-LNuml5Zuk',
    appId: '1:624760631876:ios:eaea7f3ae2095547068211',
    messagingSenderId: '624760631876',
    projectId: 'app-fam-7d4f6',
    storageBucket: 'app-fam-7d4f6.firebasestorage.app',
    iosClientId: '624760631876-2hi7bn5niibj3gl9f6g69o73l239dnnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.famIntento1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASfcDcr76cW8AFIArvZ4QAS89RGOnmNLM',
    appId: '1:624760631876:web:dbca9410bcb45a64068211',
    messagingSenderId: '624760631876',
    projectId: 'app-fam-7d4f6',
    authDomain: 'app-fam-7d4f6.firebaseapp.com',
    storageBucket: 'app-fam-7d4f6.firebasestorage.app',
    measurementId: 'G-CH6H7R2MCG',
  );
}
